# -*- coding: utf-8 -*-
"""DAtask8

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ncKaVfMmgMpRG5yKeFrFc__h0Xwnau1I
"""

!pip install pandas plotly -q

import pandas as pd
import plotly.express as px

df = pd.read_csv("Sample - Superstore.csv", encoding="latin-1")

df["Order Date"] = pd.to_datetime(df["Order Date"], format='mixed', dayfirst=False)
df["Month-Year"] = df["Order Date"].dt.to_period("M").astype(str)
df.head(5)

sales_trend = df.groupby("Month-Year")["Sales"].sum().reset_index()

fig1 = px.line(sales_trend, x="Month-Year", y="Sales",
               title="📈 Sales Over Time", markers=True)
fig1.update_xaxes(type="category")  # keeps months in order
fig1.show()

region_sales = df.groupby("Region")["Sales"].sum().reset_index()

fig2 = px.bar(region_sales, x="Region", y="Sales", color="Region",
              title="📊 Sales by Region")
fig2.show()

category_sales = df.groupby("Category")["Sales"].sum().reset_index()

fig3 = px.pie(category_sales, names="Category", values="Sales",
              title="🍩 Sales by Category", hole=0.4)
fig3.show()

fig4 = px.line(df, x="Month-Year", y="Sales", color="Region",
               title="📊 Sales Trend by Region",
               category_orders={"Month-Year": sorted(df["Month-Year"].unique())})
fig4.update_xaxes(type="category")
fig4.show()